#!/usr/bin/env perl

use 5.012;

use warnings;
use strict;

use autodie;

use Data::Dumper;

my $parser = do {
    use Regexp::Grammars;

    qr{
        #<debug: on>

        <line>

        <rule: line>
            ^
            (?: <pp_directive>
              | <directive>
              | (?: <data> | <op> )
              | (?: <label> :?)? (?: <data> | <op> )?
            )? <comment>?
            $

        <rule: pp_directive>
            \%
            (?: <include_pp_directive>
            )

        <rule: include_pp_directive>
            include "<filename=([^"]+)>"

        <rule: directive>
            (?: <bits_directive>
              | <global_directive>
              | <extern_directive>
              | <section_directive>
            )

        <rule: bits_directive>
            BITS (?: 16 | 32 | 64 )

        <rule: global_directive>
            GLOBAL <label>

        <rule: extern_directive>
            EXTERN <label>

        <rule: section_directive>
            SECTION \. (?: text | data | bss )

        <rule: label>
            [a-zA-Z_]\w+

        <rule: data>
            (?: db <[data_byte]> (?: , <[data_byte]> )*
              | dd <[data_word]> (?: , <[data_word]> )*
            )

        <rule: data_byte>
            (?: <number> | <string> )

        <rule: data_word>
            (?: <number> | <label> )

        <rule: number>
            [+\-]? (?: 0x [0-9a-f]+ | [0-9]+ )

        <rule: string>
            '[^']*'

        <rule: comment>
            ; [^\n]*

        <rule: op>
            (?: <aaa_op>
              | <aad_op>
              | <aam_op>
              | <aas_op>
              | <adc_op>
              | <add_op>
              | <and_op>
              | <arpl_op>
              | <bound_op>
              | <bsf_op>
              | <bsr_op>
              | <bt_op>
              | <btc_op>
              | <btr_op>
              | <bts_op>
              | <call_op>
              | <cbw_op>
              | <cdq_op>
              | <clc_op>
              | <cld_op>
              | <cli_op>
              | <cmc_op>
              | <cmp_op>
              | <cmpsb_op>
              | <cmpsd_op>
              | <cmpsw_op>
              | <cwd_op>
              | <cwde_op>
              | <daa_op>
              | <das_op>
              | <dec_op>
              | <div_op>
              | <equ_op>
              | <f2xm1_op>
              | <fabs_op>
              | <fadd_op>
              | <faddp_op>
              | <fbld_op>
              | <fbstp_op>
              | <fchs_op>
              | <fclex_op>
              | <fcom_op>
              | <fcomp_op>
              | <fcompp_op>
              | <fcos_op>
              | <fdecstp_op>
              | <fdisi_op>
              | <fdiv_op>
              | <fdivp_op>
              | <fdivr_op>
              | <fdivrp_op>
              | <feni_op>
              | <ffree_op>
              | <fiadd_op>
              | <ficom_op>
              | <ficomp_op>
              | <fidiv_op>
              | <fidivr_op>
              | <fild_op>
              | <fimul_op>
              | <fincstp_op>
              | <finit_op>
              | <fist_op>
              | <fistp_op>
              | <fisub_op>
              | <fisubr_op>
              | <fld_op>
              | <fld1_op>
              | <fldcw_op>
              | <fldenv_op>
              | <fldl2e_op>
              | <fldl2t_op>
              | <fldlg2_op>
              | <fldln2_op>
              | <fldpi_op>
              | <fldz_op>
              | <fmul_op>
              | <fmulp_op>
              | <fnclex_op>
              | <fndisi_op>
              | <fneni_op>
              | <fninit_op>
              | <fnop_op>
              | <fnsave_op>
              | <fnstcw_op>
              | <fnstenv_op>
              | <fnstsw_op>
              | <fpatan_op>
              | <fprem_op>
              | <fprem1_op>
              | <fptan_op>
              | <frndint_op>
              | <frstor_op>
              | <fsave_op>
              | <fscale_op>
              | <fsetpm_op>
              | <fsin_op>
              | <fsincos_op>
              | <fsqrt_op>
              | <fst_op>
              | <fstcw_op>
              | <fstenv_op>
              | <fstp_op>
              | <fstsw_op>
              | <fsub_op>
              | <fsubp_op>
              | <fsubr_op>
              | <fsubrp_op>
              | <ftst_op>
              | <fucom_op>
              | <fucomp_op>
              | <fucompp_op>
              | <fwait_op>
              | <fxam_op>
              | <fxch_op>
              | <fxtract_op>
              | <fyl2x_op>
              | <fyl2xp1_op>
              | <icebp_op>
              | <idiv_op>
              | <imul_op>
              | <in_op>
              | <inc_op>
              | <insd_op>
              | <int_op>
              | <int01_op>
              | <int03_op>
              | <int1_op>
              | <int3_op>
              | <into_op>
              | <iret_op>
              | <iretd_op>
              | <iretw_op>
              | <jcxz_op>
              | <jecxz_op>
              | <jmp_op>
              | <ja_op>
              | <jae_op>
              | <jb_op>
              | <jbe_op>
              | <jc_op>
              | <je_op>
              | <jg_op>
              | <jge_op>
              | <jl_op>
              | <jle_op>
              | <jna_op>
              | <jnae_op>
              | <jnb_op>
              | <jnbe_op>
              | <jnc_op>
              | <jne_op>
              | <jng_op>
              | <jnge_op>
              | <jnl_op>
              | <jnle_op>
              | <jno_op>
              | <jnp_op>
              | <jns_op>
              | <jnz_op>
              | <jo_op>
              | <jp_op>
              | <jpe_op>
              | <jpo_op>
              | <js_op>
              | <jz_op>
              | <lahf_op>
              | <lar_op>
              | <lds_op>
              | <lea_op>
              | <les_op>
              | <lfs_op>
              | <lgs_op>
              | <lodsb_op>
              | <lodsd_op>
              | <lodsw_op>
              | <loop_op>
              | <loope_op>
              | <loopne_op>
              | <loopnz_op>
              | <loopz_op>
              | <lsl_op>
              | <lss_op>
              | <mov_op>
              | <movsb_op>
              | <movsd_op>
              | <movsw_op>
              | <movsx_op>
              | <movzx_op>
              | <mul_op>
              | <neg_op>
              | <nop_op>
              | <not_op>
              | <or_op>
              | <out_op>
              | <outsd_op>
              | <pause_op>
              | <pop_op>
              | <popad_op>
              | <popf_op>
              | <popfd_op>
              | <popfw_op>
              | <push_op>
              | <pushad_op>
              | <pushf_op>
              | <pushfd_op>
              | <pushfw_op>
              | <rcl_op>
              | <rcr_op>
              | <resb_op>
              | <ret_op>
              | <retf_op>
              | <retn_op>
              | <rol_op>
              | <ror_op>
              | <sahf_op>
              | <sal_op>
              | <sar_op>
              | <sbb_op>
              | <scasb_op>
              | <scasd_op>
              | <scasw_op>
              | <seta_op>
              | <setae_op>
              | <setb_op>
              | <setbe_op>
              | <setc_op>
              | <sete_op>
              | <setg_op>
              | <setge_op>
              | <setl_op>
              | <setle_op>
              | <setna_op>
              | <setnae_op>
              | <setnb_op>
              | <setnbe_op>
              | <setnc_op>
              | <setne_op>
              | <setng_op>
              | <setnge_op>
              | <setnl_op>
              | <setnle_op>
              | <setno_op>
              | <setnp_op>
              | <setns_op>
              | <setnz_op>
              | <seto_op>
              | <setp_op>
              | <setpe_op>
              | <setpo_op>
              | <sets_op>
              | <setz_op>
              | <sgdt_op>
              | <shl_op>
              | <shld_op>
              | <shr_op>
              | <shrd_op>
              | <sidt_op>
              | <sldt_op>
              | <smsw_op>
              | <stc_op>
              | <std_op>
              | <sti_op>
              | <stosb_op>
              | <stosd_op>
              | <stosw_op>
              | <str_op>
              | <sub_op>
              | <test_op>
              | <verr_op>
              | <verw_op>
              | <xchg_op>
              | <xlat_op>
              | <xlatb_op>
              | <xor_op>
            )

        <rule: aaa_op>
            aaa

        <rule: aad_op>
            aad <imm>

        <rule: aam_op>
            aam <imm>

        <rule: aas_op>
            aas

        <rule: adc_op>
            adc (?: <mem> , <imm16>
                  | <mem> , <imm32>
                  | <mem> , <imm8>
                  | <mem> , <reg16>
                  | <mem> , <reg32>
                  | <mem> , <reg8>
                  | <reg16> , <mem>
                  | <reg16> , <reg16>
                  | <reg32> , <mem>
                  | <reg32> , <reg32>
                  | <reg8> , <mem>
                  | <reg8> , <reg8>
                  | <reg_al> , <imm>
                  | <reg_ax> , <imm>
                  | <reg_ax> , <sbyte16>
                  | <reg_eax> , <imm>
                  | <reg_eax> , <sbyte32>
                  | <rm16> , <imm>
                  | <rm16> , <imm8>
                  | <rm32> , <imm>
                  | <rm32> , <imm8>
                  | <rm8> , <imm>
            )

        <rule: add_op>
            add (?: <mem> , <imm16>
                  | <mem> , <imm32>
                  | <mem> , <imm8>
                  | <mem> , <reg16>
                  | <mem> , <reg32>
                  | <mem> , <reg8>
                  | <reg16> , <mem>
                  | <reg16> , <reg16>
                  | <reg32> , <mem>
                  | <reg32> , <reg32>
                  | <reg8> , <mem>
                  | <reg8> , <reg8>
                  | <reg_al> , <imm>
                  | <reg_ax> , <imm>
                  | <reg_ax> , <sbyte16>
                  | <reg_eax> , <imm>
                  | <reg_eax> , <sbyte32>
                  | <rm16> , <imm>
                  | <rm16> , <imm8>
                  | <rm32> , <imm>
                  | <rm32> , <imm8>
                  | <rm8> , <imm>
            )

        <rule: and_op>
            and (?: <mem> , <imm16>
                  | <mem> , <imm32>
                  | <mem> , <imm8>
                  | <mem> , <reg16>
                  | <mem> , <reg32>
                  | <mem> , <reg8>
                  | <reg16> , <mem>
                  | <reg16> , <reg16>
                  | <reg32> , <mem>
                  | <reg32> , <reg32>
                  | <reg8> , <mem>
                  | <reg8> , <reg8>
                  | <reg_al> , <imm>
                  | <reg_ax> , <imm>
                  | <reg_ax> , <sbyte16>
                  | <reg_eax> , <imm>
                  | <reg_eax> , <sbyte32>
                  | <rm16> , <imm>
                  | <rm16> , <imm8>
                  | <rm32> , <imm>
                  | <rm32> , <imm8>
                  | <rm8> , <imm>
            )

        <rule: arpl_op>
            arpl (?: <mem> , <reg16>
                   | <reg16> , <reg16>
            )

        <rule: bound_op>
            bound <reg32> , <mem>

        <rule: bsf_op>
            bsf (?: <reg16> , <mem>
                  | <reg16> , <reg16>
                  | <reg32> , <mem>
                  | <reg32> , <reg32>
            )

        <rule: bsr_op>
            bsr (?: <reg16> , <mem>
                  | <reg16> , <reg16>
                  | <reg32> , <mem>
                  | <reg32> , <reg32>
            )

        <rule: bt_op>
            bt (?: <mem> , <reg16>
                 | <mem> , <reg32>
                 | <reg16> , <reg16>
                 | <reg32> , <reg32>
                 | <rm16> , <imm>
                 | <rm32> , <imm>
            )

        <rule: btc_op>
            btc (?: <mem> , <reg16>
                  | <mem> , <reg32>
                  | <reg16> , <reg16>
                  | <reg32> , <reg32>
                  | <rm16> , <imm>
                  | <rm32> , <imm>
            )

        <rule: btr_op>
            btr (?: <mem> , <reg16>
                  | <mem> , <reg32>
                  | <reg16> , <reg16>
                  | <reg32> , <reg32>
                  | <rm16> , <imm>
                  | <rm32> , <imm>
            )

        <rule: bts_op>
            bts (?: <mem> , <reg16>
                  | <mem> , <reg32>
                  | <reg16> , <reg16>
                  | <reg32> , <reg32>
                  | <rm16> , <imm>
                  | <rm32> , <imm>
            )

        <rule: call_op>
            call (?: <imm>
                   | <imm16>
                   #| <imm16:imm>
                   | (?: <far> <imm16> )
                   | (?: <near> <imm16> )
                   | <imm32>
                   #| <imm32:imm>
                   | (?: <far> <imm32> )
                   | (?: <near> <imm32> )
                   #| <imm:imm>
                   #| <imm:imm16>
                   #| <imm:imm32>
                   | (?: <far> <imm> )
                   | (?: <near> <imm> )
                   | <mem>
                   | <mem16>
                   | (?: <far> <mem16> )
                   | (?: <near> <mem16> )
                   | <mem32>
                   | (?: <far> <mem32> )
                   | (?: <near> <mem32> )
                   | (?: <far> <mem> )
                   | (?: <near> <mem> )
                   | <reg16>
                   | <reg32>
            )

        <rule: cbw_op>
            cbw

        <rule: cdq_op>
            cdq

        <rule: clc_op>
            clc

        <rule: cld_op>
            cld

        <rule: cli_op>
            cli

        <rule: cmc_op>
            cmc

        <rule: cmp_op>
            cmp (?: <mem> , <imm16>
                  | <mem> , <imm32>
                  | <mem> , <imm8>
                  | <mem> , <reg16>
                  | <mem> , <reg32>
                  | <mem> , <reg8>
                  | <reg16> , <mem>
                  | <reg16> , <reg16>
                  | <reg32> , <mem>
                  | <reg32> , <reg32>
                  | <reg8> , <mem>
                  | <reg8> , <reg8>
                  | <reg_al> , <imm>
                  | <reg_ax> , <imm>
                  | <reg_ax> , <sbyte16>
                  | <reg_eax> , <imm>
                  | <reg_eax> , <sbyte32>
                  | <rm16> , <imm>
                  | <rm16> , <imm8>
                  | <rm32> , <imm>
                  | <rm32> , <imm8>
                  | <rm8> , <imm>
            )

        <rule: cmpsb_op>
            cmpsb

        <rule: cmpsd_op>
            cmpsd

        <rule: cmpsw_op>
            cmpsw

        <rule: cwd_op>
            cwd

        <rule: cwde_op>
            cwde

        <rule: daa_op>
            daa

        <rule: das_op>
            das

        <rule: dec_op>
            dec (?: <reg16>
                  | <reg32>
                  | <rm16>
                  | <rm32>
                  | <rm8>
            )

        <rule: div_op>
            div (?: <rm16>
                  | <rm32>
                  | <rm8>
            )

        <rule: equ_op>
            equ (?: <imm>
                  #| <imm:imm>
            )

        <rule: f2xm1_op>
            f2xm1

        <rule: fabs_op>
            fabs

        <rule: fadd_op>
            fadd (?: <fpu0> , <fpureg>
                   | <fpureg>
                   | <fpureg> , <fpu0>
                   | (?: <to> <fpureg> )
                   | <mem32>
                   | <mem64>
            )

        <rule: faddp_op>
            faddp (?: <fpureg>
                    | <fpureg> , <fpu0>
            )

        <rule: fbld_op>
            fbld (?: <mem>
                   | <mem80>
            )

        <rule: fbstp_op>
            fbstp (?: <mem>
                    | <mem80>
            )

        <rule: fchs_op>
            fchs

        <rule: fclex_op>
            fclex

        <rule: fcom_op>
            fcom (?: <fpu0> , <fpureg>
                   | <fpureg>
                   | <mem32>
                   | <mem64>
            )

        <rule: fcomp_op>
            fcomp (?: <fpu0> , <fpureg>
                    | <fpureg>
                    | <mem32>
                    | <mem64>
            )

        <rule: fcompp_op>
            fcompp

        <rule: fcos_op>
            fcos

        <rule: fdecstp_op>
            fdecstp

        <rule: fdisi_op>
            fdisi

        <rule: fdiv_op>
            fdiv (?: <fpu0> , <fpureg>
                   | <fpureg>
                   | <fpureg> , <fpu0>
                   | (?: <to> <fpureg> )
                   | <mem32>
                   | <mem64>
            )

        <rule: fdivp_op>
            fdivp (?: <fpureg>
                    | <fpureg> , <fpu0>
            )

        <rule: fdivr_op>
            fdivr (?: <fpu0> , <fpureg>
                    | <fpureg>
                    | <fpureg> , <fpu0>
                    | (?: <to> <fpureg> )
                    | <mem32>
                    | <mem64>
            )

        <rule: fdivrp_op>
            fdivrp (?: <fpureg>
                     | <fpureg> , <fpu0>
            )

        <rule: feni_op>
            feni

        <rule: ffree_op>
            ffree <fpureg>

        <rule: fiadd_op>
            fiadd (?: <mem16>
                    | <mem32>
            )

        <rule: ficom_op>
            ficom (?: <mem16>
                    | <mem32>
            )

        <rule: ficomp_op>
            ficomp (?: <mem16>
                     | <mem32>
            )

        <rule: fidiv_op>
            fidiv (?: <mem16>
                    | <mem32>
            )

        <rule: fidivr_op>
            fidivr (?: <mem16>
                     | <mem32>
            )

        <rule: fild_op>
            fild (?: <mem16>
                   | <mem32>
                   | <mem64>
            )

        <rule: fimul_op>
            fimul (?: <mem16>
                    | <mem32>
            )

        <rule: fincstp_op>
            fincstp

        <rule: finit_op>
            finit

        <rule: fist_op>
            fist (?: <mem16>
                   | <mem32>
            )

        <rule: fistp_op>
            fistp (?: <mem16>
                    | <mem32>
                    | <mem64>
            )

        <rule: fisub_op>
            fisub (?: <mem16>
                    | <mem32>
            )

        <rule: fisubr_op>
            fisubr (?: <mem16>
                     | <mem32>
            )

        <rule: fld_op>
            fld (?: <fpureg>
                  | <mem32>
                  | <mem64>
                  | <mem80>
            )

        <rule: fld1_op>
            fld1

        <rule: fldcw_op>
            fldcw <mem>

        <rule: fldenv_op>
            fldenv <mem>

        <rule: fldl2e_op>
            fldl2e

        <rule: fldl2t_op>
            fldl2t

        <rule: fldlg2_op>
            fldlg2

        <rule: fldln2_op>
            fldln2

        <rule: fldpi_op>
            fldpi

        <rule: fldz_op>
            fldz

        <rule: fmul_op>
            fmul (?: <fpu0> , <fpureg>
                   | <fpureg>
                   | <fpureg> , <fpu0>
                   | (?: <to> <fpureg> )
                   | <mem32>
                   | <mem64>
            )

        <rule: fmulp_op>
            fmulp (?: <fpureg>
                    | <fpureg> , <fpu0>
            )

        <rule: fnclex_op>
            fnclex

        <rule: fndisi_op>
            fndisi

        <rule: fneni_op>
            fneni

        <rule: fninit_op>
            fninit

        <rule: fnop_op>
            fnop

        <rule: fnsave_op>
            fnsave <mem>

        <rule: fnstcw_op>
            fnstcw <mem>

        <rule: fnstenv_op>
            fnstenv <mem>

        <rule: fnstsw_op>
            fnstsw (?: <mem>
                     | <reg_ax>
            )

        <rule: fpatan_op>
            fpatan

        <rule: fprem_op>
            fprem

        <rule: fprem1_op>
            fprem1

        <rule: fptan_op>
            fptan

        <rule: frndint_op>
            frndint

        <rule: frstor_op>
            frstor <mem>

        <rule: fsave_op>
            fsave <mem>

        <rule: fscale_op>
            fscale

        <rule: fsetpm_op>
            fsetpm

        <rule: fsin_op>
            fsin

        <rule: fsincos_op>
            fsincos

        <rule: fsqrt_op>
            fsqrt

        <rule: fst_op>
            fst (?: <fpureg>
                  | <mem32>
                  | <mem64>
            )

        <rule: fstcw_op>
            fstcw <mem>

        <rule: fstenv_op>
            fstenv <mem>

        <rule: fstp_op>
            fstp (?: <fpureg>
                   | <mem32>
                   | <mem64>
                   | <mem80>
            )

        <rule: fstsw_op>
            fstsw (?: <mem>
                    | <reg_ax>
            )

        <rule: fsub_op>
            fsub (?: <fpu0> , <fpureg>
                   | <fpureg>
                   | <fpureg> , <fpu0>
                   | (?: <to> <fpureg> )
                   | <mem32>
                   | <mem64>
            )

        <rule: fsubp_op>
            fsubp (?: <fpureg>
                    | <fpureg> , <fpu0>
            )

        <rule: fsubr_op>
            fsubr (?: <fpu0> , <fpureg>
                    | <fpureg>
                    | <fpureg> , <fpu0>
                    | (?: <to> <fpureg> )
                    | <mem32>
                    | <mem64>
            )

        <rule: fsubrp_op>
            fsubrp (?: <fpureg>
                     | <fpureg> , <fpu0>
            )

        <rule: ftst_op>
            ftst

        <rule: fucom_op>
            fucom (?: <fpu0> , <fpureg>
                    | <fpureg>
            )

        <rule: fucomp_op>
            fucomp (?: <fpu0> , <fpureg>
                     | <fpureg>
            )

        <rule: fucompp_op>
            fucompp

        <rule: fwait_op>
            fwait

        <rule: fxam_op>
            fxam

        <rule: fxch_op>
            fxch (?: <fpu0> , <fpureg>
                   | <fpureg>
                   | <fpureg> , <fpu0>
            )

        <rule: fxtract_op>
            fxtract

        <rule: fyl2x_op>
            fyl2x

        <rule: fyl2xp1_op>
            fyl2xp1

        <rule: icebp_op>
            icebp

        <rule: idiv_op>
            idiv (?: <rm16>
                   | <rm32>
                   | <rm8>
            )

        <rule: imul_op>
            imul (?: <reg16> , <mem>
                   | <reg16> , <reg16>
                   | <reg32> , <imm>
                   | <reg32> , <imm32>
                   | <reg32> , <imm8>
                   | <reg32> , <mem>
                   | <reg32> , <mem> , <imm>
                   | <reg32> , <mem> , <imm32>
                   | <reg32> , <mem> , <imm8>
                   | <reg32> , <mem> , <sbyte32>
                   | <reg32> , <reg32>
                   | <reg32> , <reg32> , <imm>
                   | <reg32> , <reg32> , <imm32>
                   | <reg32> , <reg32> , <imm8>
                   | <reg32> , <reg32> , <sbyte32>
                   | <reg32> , <sbyte32>
                   | <rm16>
                   | <rm32>
                   | <rm8>
            )

        <rule: in_op>
            in (?: <reg_al> , <imm>
                 | <reg_al> , <reg_dx>
                 | <reg_ax> , <imm>
                 | <reg_ax> , <reg_dx>
                 | <reg_eax> , <imm>
                 | <reg_eax> , <reg_dx>
            )

        <rule: inc_op>
            inc (?: <reg16>
                  | <reg32>
                  | <rm16>
                  | <rm32>
                  | <rm8>
            )

        <rule: insd_op>
            insd

        <rule: int_op>
            int <imm>

        <rule: int01_op>
            int01

        <rule: int03_op>
            int03

        <rule: int1_op>
            int1

        <rule: int3_op>
            int3

        <rule: into_op>
            into

        <rule: iret_op>
            iret

        <rule: iretd_op>
            iretd

        <rule: iretw_op>
            iretw

        <rule: jcxz_op>
            jcxz <imm>

        <rule: jecxz_op>
            jecxz <imm>

        <rule: jmp_op>
            jmp (?: <imm>
                  | <imm16>
                  #| <imm16:imm>
                  | (?: <far> <imm16> )
                  | (?: <near> <imm16> )
                  | <imm32>
                  #| <imm32:imm>
                  | (?: <far> <imm32> )
                  | (?: <near> <imm32> )
                  #| <imm:imm>
                  #| <imm:imm16>
                  #| <imm:imm32>
                  | (?: <far> <imm> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
                  | <mem>
                  | <mem16>
                  | (?: <far> <mem16> )
                  | (?: <near> <mem16> )
                  | <mem32>
                  | (?: <far> <mem32> )
                  | (?: <near> <mem32> )
                  | (?: <far> <mem> )
                  | (?: <near> <mem> )
                  | <reg16>
                  | <reg32>
            )

        <rule: ja_op>
            ja (?: <imm>
                 | (?: <near> <imm16> )
                 | (?: <near> <imm32> )
                 | (?: <near> <imm> )
                 | (?: <short> <imm> )
            )

        <rule: jae_op>
            jae (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: jb_op>
            jb (?: <imm>
                 | (?: <near> <imm16> )
                 | (?: <near> <imm32> )
                 | (?: <near> <imm> )
                 | (?: <short> <imm> )
            )

        <rule: jbe_op>
            jbe (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: jc_op>
            jc (?: <imm>
                 | (?: <near> <imm16> )
                 | (?: <near> <imm32> )
                 | (?: <near> <imm> )
                 | (?: <short> <imm> )
            )

        <rule: je_op>
            je (?: <imm>
                 | (?: <near> <imm16> )
                 | (?: <near> <imm32> )
                 | (?: <near> <imm> )
                 | (?: <short> <imm> )
            )

        <rule: jg_op>
            jg (?: <imm>
                 | (?: <near> <imm16> )
                 | (?: <near> <imm32> )
                 | (?: <near> <imm> )
                 | (?: <short> <imm> )
            )

        <rule: jge_op>
            jge (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: jl_op>
            jl (?: <imm>
                 | (?: <near> <imm16> )
                 | (?: <near> <imm32> )
                 | (?: <near> <imm> )
                 | (?: <short> <imm> )
            )

        <rule: jle_op>
            jle (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: jna_op>
            jna (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: jnae_op>
            jnae (?: <imm>
                   | (?: <near> <imm16> )
                   | (?: <near> <imm32> )
                   | (?: <near> <imm> )
                   | (?: <short> <imm> )
            )

        <rule: jnb_op>
            jnb (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: jnbe_op>
            jnbe (?: <imm>
                   | (?: <near> <imm16> )
                   | (?: <near> <imm32> )
                   | (?: <near> <imm> )
                   | (?: <short> <imm> )
            )

        <rule: jnc_op>
            jnc (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: jne_op>
            jne (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: jng_op>
            jng (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: jnge_op>
            jnge (?: <imm>
                   | (?: <near> <imm16> )
                   | (?: <near> <imm32> )
                   | (?: <near> <imm> )
                   | (?: <short> <imm> )
            )

        <rule: jnl_op>
            jnl (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: jnle_op>
            jnle (?: <imm>
                   | (?: <near> <imm16> )
                   | (?: <near> <imm32> )
                   | (?: <near> <imm> )
                   | (?: <short> <imm> )
            )

        <rule: jno_op>
            jno (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: jnp_op>
            jnp (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: jns_op>
            jns (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: jnz_op>
            jnz (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: jo_op>
            jo (?: <imm>
                 | (?: <near> <imm16> )
                 | (?: <near> <imm32> )
                 | (?: <near> <imm> )
                 | (?: <short> <imm> )
            )

        <rule: jp_op>
            jp (?: <imm>
                 | (?: <near> <imm16> )
                 | (?: <near> <imm32> )
                 | (?: <near> <imm> )
                 | (?: <short> <imm> )
            )

        <rule: jpe_op>
            jpe (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: jpo_op>
            jpo (?: <imm>
                  | (?: <near> <imm16> )
                  | (?: <near> <imm32> )
                  | (?: <near> <imm> )
                  | (?: <short> <imm> )
            )

        <rule: js_op>
            js (?: <imm>
                 | (?: <near> <imm16> )
                 | (?: <near> <imm32> )
                 | (?: <near> <imm> )
                 | (?: <short> <imm> )
            )

        <rule: jz_op>
            jz (?: <imm>
                 | (?: <near> <imm16> )
                 | (?: <near> <imm32> )
                 | (?: <near> <imm> )
                 | (?: <short> <imm> )
            )

        <rule: lahf_op>
            lahf

        <rule: lar_op>
            lar (?: <reg16> , <mem>
                  | <reg16> , <reg16>
                  | <reg16> , <reg32>
                  | <reg32> , <mem>
                  | <reg32> , <reg16>
                  | <reg32> , <reg32>
            )

        <rule: lds_op>
            lds (?: <reg16> , <mem>
                  | <reg32> , <mem>
            )

        <rule: lea_op>
            lea (?: <reg16> , <mem>
                  | <reg32> , <mem>
            )

        <rule: les_op>
            les (?: <reg16> , <mem>
                  | <reg32> , <mem>
            )

        <rule: lfs_op>
            lfs (?: <reg16> , <mem>
                  | <reg32> , <mem>
            )

        <rule: lgs_op>
            lgs (?: <reg16> , <mem>
                  | <reg32> , <mem>
            )

        <rule: lodsb_op>
            lodsb

        <rule: lodsd_op>
            lodsd

        <rule: lodsw_op>
            lodsw

        <rule: loop_op>
            loop (?: <imm>
                   | <imm> , <reg_cx>
                   | <imm> , <reg_ecx>
            )

        <rule: loope_op>
            loope (?: <imm>
                    | <imm> , <reg_cx>
                    | <imm> , <reg_ecx>
            )

        <rule: loopne_op>
            loopne (?: <imm>
                     | <imm> , <reg_cx>
                     | <imm> , <reg_ecx>
            )

        <rule: loopnz_op>
            loopnz (?: <imm>
                     | <imm> , <reg_cx>
                     | <imm> , <reg_ecx>
            )

        <rule: loopz_op>
            loopz (?: <imm>
                    | <imm> , <reg_cx>
                    | <imm> , <reg_ecx>
            )

        <rule: lsl_op>
            lsl (?: <reg16> , <mem>
                  | <reg16> , <reg16>
                  | <reg16> , <reg32>
                  | <reg32> , <mem>
                  | <reg32> , <reg16>
                  | <reg32> , <reg32>
            )

        <rule: lss_op>
            lss (?: <reg16> , <mem>
                  | <reg32> , <mem>
            )

        <rule: mov_op>
            mov (?: <mem> , <imm16>
                  | <mem> , <imm32>
                  | <mem> , <imm8>
                  | <mem> , <reg16>
                  | <mem> , <reg32>
                  | <mem> , <reg8>
                  | <mem> , <reg_sreg>
                  | <mem_offs> , <reg_al>
                  | <mem_offs> , <reg_ax>
                  | <mem_offs> , <reg_eax>
                  | <reg16> , <imm>
                  | <reg16> , <mem>
                  | <reg16> , <reg16>
                  | <reg16> , <reg_sreg>
                  | <reg32> , <imm>
                  | <reg32> , <mem>
                  | <reg32> , <reg32>
                  | <reg32> , <reg_sreg>
                  | <reg32> , <reg_treg>
                  | <reg8> , <imm>
                  | <reg8> , <mem>
                  | <reg8> , <reg8>
                  | <reg_al> , <mem_offs>
                  | <reg_ax> , <mem_offs>
                  | <reg_eax> , <mem_offs>
                  | <reg_sreg> , <mem>
                  | <reg_sreg> , <reg16>
                  | <reg_sreg> , <reg32>
                  | <reg_treg> , <reg32>
                  | <rm16> , <imm>
                  | <rm32> , <imm>
                  | <rm8> , <imm>
            )

        <rule: movsb_op>
            movsb

        <rule: movsd_op>
            movsd

        <rule: movsw_op>
            movsw

        <rule: movsx_op>
            movsx (?: <reg16> , <mem>
                    | <reg16> , <reg8>
                    | <reg32> , <rm16>
                    | <reg32> , <rm8>
            )

        <rule: movzx_op>
            movzx (?: <reg16> , <mem>
                    | <reg16> , <reg8>
                    | <reg32> , <rm16>
                    | <reg32> , <rm8>
            )

        <rule: mul_op>
            mul (?: <rm16>
                  | <rm32>
                  | <rm8>
            )

        <rule: neg_op>
            neg (?: <rm16>
                  | <rm32>
                  | <rm8>
            )

        <rule: nop_op>
            nop

        <rule: not_op>
            not (?: <rm16>
                  | <rm32>
                  | <rm8>
            )

        <rule: or_op>
            or (?: <mem> , <imm16>
                 | <mem> , <imm32>
                 | <mem> , <imm8>
                 | <mem> , <reg16>
                 | <mem> , <reg32>
                 | <mem> , <reg8>
                 | <reg16> , <mem>
                 | <reg16> , <reg16>
                 | <reg32> , <mem>
                 | <reg32> , <reg32>
                 | <reg8> , <mem>
                 | <reg8> , <reg8>
                 | <reg_al> , <imm>
                 | <reg_ax> , <imm>
                 | <reg_ax> , <sbyte16>
                 | <reg_eax> , <imm>
                 | <reg_eax> , <sbyte32>
                 | <rm16> , <imm>
                 | <rm16> , <imm8>
                 | <rm32> , <imm>
                 | <rm32> , <imm8>
                 | <rm8> , <imm>
            )

        <rule: out_op>
            out (?: <imm> , <reg_al>
                  | <imm> , <reg_ax>
                  | <imm> , <reg_eax>
                  | <reg_dx> , <reg_al>
                  | <reg_dx> , <reg_ax>
                  | <reg_dx> , <reg_eax>
            )

        <rule: outsd_op>
            outsd

        <rule: pause_op>
            pause

        <rule: pop_op>
            pop (?: <reg16>
                  | <reg32>
                  | <reg_dess>
                  | <reg_fsgs>
                  | <rm16>
                  | <rm32>
            )

        <rule: popad_op>
            popad

        <rule: popf_op>
            popf

        <rule: popfd_op>
            popfd

        <rule: popfw_op>
            popfw

        <rule: push_op>
            push (?: <imm32>
                   | <reg16>
                   | <reg32>
                   | <reg_cs>
                   | <reg_dess>
                   | <reg_fsgs>
                   | <rm16>
                   | <rm32>
            )

        <rule: pushad_op>
            pushad

        <rule: pushf_op>
            pushf

        <rule: pushfd_op>
            pushfd

        <rule: pushfw_op>
            pushfw

        <rule: rcl_op>
            rcl (?: <rm16> , <reg_cl>
                  | <rm16> , <unity>
                  | <rm32> , <imm>
                  | <rm32> , <reg_cl>
                  | <rm32> , <unity>
                  | <rm8> , <reg_cl>
                  | <rm8> , <unity>
            )

        <rule: rcr_op>
            rcr (?: <rm16> , <reg_cl>
                  | <rm16> , <unity>
                  | <rm32> , <imm>
                  | <rm32> , <reg_cl>
                  | <rm32> , <unity>
                  | <rm8> , <reg_cl>
                  | <rm8> , <unity>
            )

        <rule: resb_op>
            resb <imm>

        <rule: ret_op>
            ret <imm>

        <rule: retf_op>
            retf <imm>

        <rule: retn_op>
            retn <imm>

        <rule: rol_op>
            rol (?: <rm16> , <reg_cl>
                  | <rm16> , <unity>
                  | <rm32> , <imm>
                  | <rm32> , <reg_cl>
                  | <rm32> , <unity>
                  | <rm8> , <reg_cl>
                  | <rm8> , <unity>
            )

        <rule: ror_op>
            ror (?: <rm16> , <reg_cl>
                  | <rm16> , <unity>
                  | <rm32> , <imm>
                  | <rm32> , <reg_cl>
                  | <rm32> , <unity>
                  | <rm8> , <reg_cl>
                  | <rm8> , <unity>
            )

        <rule: sahf_op>
            sahf

        <rule: sal_op>
            sal (?: <rm16> , <reg_cl>
                  | <rm16> , <unity>
                  | <rm32> , <imm>
                  | <rm32> , <reg_cl>
                  | <rm32> , <unity>
                  | <rm8> , <reg_cl>
                  | <rm8> , <unity>
            )

        <rule: sar_op>
            sar (?: <rm16> , <reg_cl>
                  | <rm16> , <unity>
                  | <rm32> , <imm>
                  | <rm32> , <reg_cl>
                  | <rm32> , <unity>
                  | <rm8> , <reg_cl>
                  | <rm8> , <unity>
            )

        <rule: sbb_op>
            sbb (?: <mem> , <imm16>
                  | <mem> , <imm32>
                  | <mem> , <imm8>
                  | <mem> , <reg16>
                  | <mem> , <reg32>
                  | <mem> , <reg8>
                  | <reg16> , <mem>
                  | <reg16> , <reg16>
                  | <reg32> , <mem>
                  | <reg32> , <reg32>
                  | <reg8> , <mem>
                  | <reg8> , <reg8>
                  | <reg_al> , <imm>
                  | <reg_ax> , <imm>
                  | <reg_ax> , <sbyte16>
                  | <reg_eax> , <imm>
                  | <reg_eax> , <sbyte32>
                  | <rm16> , <imm>
                  | <rm16> , <imm8>
                  | <rm32> , <imm>
                  | <rm32> , <imm8>
                  | <rm8> , <imm>
            )

        <rule: scasb_op>
            scasb

        <rule: scasd_op>
            scasd

        <rule: scasw_op>
            scasw

        <rule: seta_op>
            seta (?: <mem>
                   | <reg8>
            )

        <rule: setae_op>
            setae (?: <mem>
                    | <reg8>
            )

        <rule: setb_op>
            setb (?: <mem>
                   | <reg8>
            )

        <rule: setbe_op>
            setbe (?: <mem>
                    | <reg8>
            )

        <rule: setc_op>
            setc (?: <mem>
                   | <reg8>
            )

        <rule: sete_op>
            sete (?: <mem>
                   | <reg8>
            )

        <rule: setg_op>
            setg (?: <mem>
                   | <reg8>
            )

        <rule: setge_op>
            setge (?: <mem>
                    | <reg8>
            )

        <rule: setl_op>
            setl (?: <mem>
                   | <reg8>
            )

        <rule: setle_op>
            setle (?: <mem>
                    | <reg8>
            )

        <rule: setna_op>
            setna (?: <mem>
                    | <reg8>
            )

        <rule: setnae_op>
            setnae (?: <mem>
                     | <reg8>
            )

        <rule: setnb_op>
            setnb (?: <mem>
                    | <reg8>
            )

        <rule: setnbe_op>
            setnbe (?: <mem>
                     | <reg8>
            )

        <rule: setnc_op>
            setnc (?: <mem>
                    | <reg8>
            )

        <rule: setne_op>
            setne (?: <mem>
                    | <reg8>
            )

        <rule: setng_op>
            setng (?: <mem>
                    | <reg8>
            )

        <rule: setnge_op>
            setnge (?: <mem>
                     | <reg8>
            )

        <rule: setnl_op>
            setnl (?: <mem>
                    | <reg8>
            )

        <rule: setnle_op>
            setnle (?: <mem>
                     | <reg8>
            )

        <rule: setno_op>
            setno (?: <mem>
                    | <reg8>
            )

        <rule: setnp_op>
            setnp (?: <mem>
                    | <reg8>
            )

        <rule: setns_op>
            setns (?: <mem>
                    | <reg8>
            )

        <rule: setnz_op>
            setnz (?: <mem>
                    | <reg8>
            )

        <rule: seto_op>
            seto (?: <mem>
                   | <reg8>
            )

        <rule: setp_op>
            setp (?: <mem>
                   | <reg8>
            )

        <rule: setpe_op>
            setpe (?: <mem>
                    | <reg8>
            )

        <rule: setpo_op>
            setpo (?: <mem>
                    | <reg8>
            )

        <rule: sets_op>
            sets (?: <mem>
                   | <reg8>
            )

        <rule: setz_op>
            setz (?: <mem>
                   | <reg8>
            )

        <rule: sgdt_op>
            sgdt <mem>

        <rule: shl_op>
            shl (?: <rm16> , <reg_cl>
                  | <rm16> , <unity>
                  | <rm32> , <imm>
                  | <rm32> , <reg_cl>
                  | <rm32> , <unity>
                  | <rm8> , <reg_cl>
                  | <rm8> , <unity>
            )

        <rule: shld_op>
            shld (?: <mem> , <reg16> , <imm>
                   | <mem> , <reg16> , <reg_cl>
                   | <mem> , <reg32> , <imm>
                   | <mem> , <reg32> , <reg_cl>
                   | <reg16> , <reg16> , <imm>
                   | <reg16> , <reg16> , <reg_cl>
                   | <reg32> , <reg32> , <imm>
                   | <reg32> , <reg32> , <reg_cl>
            )

        <rule: shr_op>
            shr (?: <rm16> , <reg_cl>
                  | <rm16> , <unity>
                  | <rm32> , <imm>
                  | <rm32> , <reg_cl>
                  | <rm32> , <unity>
                  | <rm8> , <reg_cl>
                  | <rm8> , <unity>
            )

        <rule: shrd_op>
            shrd (?: <mem> , <reg16> , <imm>
                   | <mem> , <reg16> , <reg_cl>
                   | <mem> , <reg32> , <imm>
                   | <mem> , <reg32> , <reg_cl>
                   | <reg16> , <reg16> , <imm>
                   | <reg16> , <reg16> , <reg_cl>
                   | <reg32> , <reg32> , <imm>
                   | <reg32> , <reg32> , <reg_cl>
            )

        <rule: sidt_op>
            sidt <mem>

        <rule: sldt_op>
            sldt (?: <mem>
                   | <mem16>
                   | <reg16>
                   | <reg32>
            )

        <rule: smsw_op>
            smsw (?: <mem>
                   | <mem16>
                   | <reg16>
                   | <reg32>
            )

        <rule: stc_op>
            stc

        <rule: std_op>
            std

        <rule: sti_op>
            sti

        <rule: stosb_op>
            stosb

        <rule: stosd_op>
            stosd

        <rule: stosw_op>
            stosw

        <rule: str_op>
            str (?: <mem>
                  | <mem16>
                  | <reg16>
                  | <reg32>
            )

        <rule: sub_op>
            sub (?: <mem> , <imm16>
                  | <mem> , <imm32>
                  | <mem> , <imm8>
                  | <mem> , <reg16>
                  | <mem> , <reg32>
                  | <mem> , <reg8>
                  | <reg16> , <mem>
                  | <reg16> , <reg16>
                  | <reg32> , <mem>
                  | <reg32> , <reg32>
                  | <reg8> , <mem>
                  | <reg8> , <reg8>
                  | <reg_al> , <imm>
                  | <reg_ax> , <imm>
                  | <reg_ax> , <sbyte16>
                  | <reg_eax> , <imm>
                  | <reg_eax> , <sbyte32>
                  | <rm16> , <imm>
                  | <rm16> , <imm8>
                  | <rm32> , <imm>
                  | <rm32> , <imm8>
                  | <rm8> , <imm>
            )

        <rule: test_op>
            test (?: <mem> , <imm16>
                   | <mem> , <imm32>
                   | <mem> , <imm8>
                   | <mem> , <reg16>
                   | <mem> , <reg32>
                   | <mem> , <reg8>
                   | <reg16> , <mem>
                   | <reg16> , <reg16>
                   | <reg32> , <mem>
                   | <reg32> , <reg32>
                   | <reg8> , <mem>
                   | <reg8> , <reg8>
                   | <reg_al> , <imm>
                   | <reg_ax> , <imm>
                   | <reg_eax> , <imm>
                   | <rm16> , <imm>
                   | <rm32> , <imm>
                   | <rm8> , <imm>
            )

        <rule: verr_op>
            verr (?: <mem>
                   | <mem16>
                   | <reg16>
            )

        <rule: verw_op>
            verw (?: <mem>
                   | <mem16>
                   | <reg16>
            )

        <rule: xchg_op>
            xchg (?: <mem> , <reg16>
                   | <mem> , <reg32>
                   | <mem> , <reg8>
                   | <reg16> , <mem>
                   | <reg16> , <reg16>
                   | <reg16> , <reg_ax>
                   | <reg32> , <mem>
                   | <reg32> , <reg32>
                   | <reg32na> , <reg_eax>
                   | <reg8> , <mem>
                   | <reg8> , <reg8>
                   | <reg_ax> , <reg16>
                   | <reg_eax> , <reg32na>
                   | <reg_eax> , <reg_eax>
            )

        <rule: xlat_op>
            xlat

        <rule: xlatb_op>
            xlatb

        <rule: xor_op>
            xor (?: <mem> , <imm16>
                  | <mem> , <imm32>
                  | <mem> , <imm8>
                  | <mem> , <reg16>
                  | <mem> , <reg32>
                  | <mem> , <reg8>
                  | <reg16> , <mem>
                  | <reg16> , <reg16>
                  | <reg32> , <mem>
                  | <reg32> , <reg32>
                  | <reg8> , <mem>
                  | <reg8> , <reg8>
                  | <reg_al> , <imm>
                  | <reg_ax> , <imm>
                  | <reg_ax> , <sbyte16>
                  | <reg_eax> , <imm>
                  | <reg_eax> , <sbyte32>
                  | <rm16> , <imm>
                  | <rm16> , <imm8>
                  | <rm32> , <imm>
                  | <rm32> , <imm8>
                  | <rm8> , <imm>
            )

        <rule: mem>
            <cast>?
            \[
            <[mem_operand]> (?: <[mem_operator]> <[mem_operand]> )*
            \]
        
        <rule: mem_operand>
            (?: <reg32> | <label> | <number> )

        <rule: mem_operator>
            [+\-*]

        <rule: mem8>
            <mem>

        <rule: mem16>
            <mem>

        <rule: mem32>
            <mem>

        <rule: mem64>
            <...>

        <rule: mem80>
            <...>

        <rule: mem_offs>
            <...>

        <rule: imm>
            (?: <cast>? <number> | <label> )

        <rule: imm8>
            <imm>

        <rule: imm16>
            <imm>

        <rule: imm32>
            <imm>

        <rule: sbyte16>
            <...>

        <rule: sbyte32>
            <...>

        <rule: unity>
            <...>

        <rule: reg8>
            (?: al | ah | bl | bh | cl | ch | dl | dh )

        <rule: reg16>
            (?: ax | bx | cx | dx | sp | bp | si | di )

        <rule: reg32>
            (?: eax | ebx | ecx | edx | esp | ebp | esi | edi )

        <rule: reg32na>
            <...>

        <rule: reg_al>
            <...>

        <rule: reg_cl>
            <...>

        <rule: reg_ax>
            <...>

        <rule: reg_cx>
            <...>

        <rule: reg_dx>
            <...>

        <rule: reg_cs>
            <...>

        <rule: reg_eax>
            <...>

        <rule: reg_ecx>
            <...>

        <rule: reg_sreg>
            <...>

        <rule: reg_treg>
            <...>

        <rule: reg_fsgs>
            <...>

        <rule: reg_dess>
            <...>

        <rule: fpureg>
            <...>

        <rule: fpu0>
            <...>

        <rule: rm8>
            (?: <reg8> | <mem8> )

        <rule: rm16>
            (?: <reg16> | <mem16> )

        <rule: rm32>
            (?: <reg32> | <mem32> )

        <rule: far>
            far

        <rule: near>
            near

        <rule: short>
            short

        <rule: to>
            <...>

        <rule: cast>
            (?: byte | word | dword )
    }x;
};

while ( my $line = <STDIN> ) {
    if ( $line =~ $parser ) {
        #print Dumper \%/;
        print "$. $line";
    }
    else {
        die "parse failed at line $.: $line";
    }
}
