#!/usr/bin/env perl

use 5.012;

use warnings;
use strict;
use autodie;

my @want = qw(386);
my @nowant = qw(UNDOC PRIV AMD);

my @conds = qw(a ae b be c e g ge l le na nae nb nbe nc ne ng nge nl nle no np ns nz o p pe po s z);

open my $fh, "<", "insns.dat";

my %ops;

while (my $line = <$fh>) {
    next if $line =~ m/^;/ or $line =~ m/^\s*$/;
    chomp $line;

    my ($op, $args, @rest) = split /\t+/, $line;

    my %flags = map { $_ => 1 } split ',', pop @rest;
    next if not %flags ~~ @want;
    next if %flags ~~ @nowant;

    if ($op =~ m/cc$/)
    {
        for my $cond (@conds) {
            my $cond_op = $op;
            $cond_op =~ s/cc$/$cond/;
            push @{$ops{$cond_op}}, $args;
        }
    }
    else {
        push @{$ops{$op}}, $args;
    }
}

for my $op (sort keys %ops) {
    my $lc_op = lc $op;
    say "        <rule: ".$lc_op."_op>";

    my @argrules;

    for my $args (sort @{$ops{$op}}) {
        next if $args eq "void";
        my @args = split ',', $args;

        for my $arg (
        push @argrules, '<'.join('> , <', @args).'>';
    }

    given (scalar @argrules) {
        when (0) {
            say "            $lc_op";
        }
        when (1) {
            say "            $lc_op $argrules[0]";
        }
        default {
            print "            $lc_op (?: ";
            print join "\n"." " x (length ($lc_op) + 15)."| ", @argrules;
            print "\n            )\n";
        }
    }

    say "";
}
